- name: Update packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install packages
  package:
    name: "{{ packages }}"
    state: latest

- name: Disable SSH password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable passwordless sudo for "{{ username }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: Restart SSH daemon
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed
